export const API_URL = 'http://localhost:5076/api';
export const API_URL_QUESTIONS = `${API_URL}/Question`;
export const API_URL_DESTINATIONS = `${API_URL}/Answer`;
export const TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZHNsb3phbm92QGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwianRpIjoiZGNjYjdiNjItNDM0OS00MjdjLWI5NDAtMWZmZjZjMDNkMjUzIiwiZXhwIjoxNzQyNjA5NDE5LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1MDc2IiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTA3NiJ9.H2ipoldghqUsKk9Un4s87Y-rDsNKsxTavq5e0fJOaA4';